CREATE PROCEDURE "SMC_APM_REG_ESCENARIODET"
(
	CODIGO INT,
	DOCENTRY INT,
	MONTO DECIMAL(16,2),
	USUARIOCONECTADO VARCHAR(50),
	TIPODOCUMENTO VARCHAR(50),
	NROCUOTA INT,
	LINEAASIENTO INT,
	CUENTAPROVEEDOR NVARCHAR(50),
	CODIGOBANCO NVARCHAR(30),
	CARDCODE_FACTO NVARCHAR(50),
	CARDNAME_FACTO NVARCHAR(250)
)
AS
BEGIN
--select * from "@SMC_APM_ESCDET"
	INSERT INTO "@SMC_APM_ESCDET"
	(
		"Code",
	 	"Name",
	 	"U_SMC_ESCCAB",
	 	"U_SMC_DOCENTRY",
	 	"U_SMC_MONTO",
	 	"U_SMC_MARCA",
	 	"U_SMC_3RET",
	 	"U_SMC_3LIB",
	 	"U_SMC_REG",
	 	"U_SMC_PAGO",
	 	"U_SMC_TIPO_DOCUMENTO",
	 	"U_EXP_NROCUOTA",
	 	"U_EXP_LINEAASIENTO",
	 	"U_EXP_CTAP",
	 	"U_EXP_BNCP",
	 	"U_EXD_CARDCODE_FACTO",
	 	"U_EXD_CARDNAME_FACTO"
	)
	VALUES
	(
		CAST(:DOCENTRY AS VARCHAR) || CAST(:CODIGO AS VARCHAR)|| CAST(:NROCUOTA AS VARCHAR) || CAST(:LINEAASIENTO AS VARCHAR),--||CAST(cast(:MONTO as numeric(18,0)) AS VARCHAR),
		CAST(:DOCENTRY AS VARCHAR) || CAST(:CODIGO AS VARCHAR)|| CAST(:NROCUOTA AS VARCHAR) || CAST(:LINEAASIENTO AS VARCHAR),--||CAST(cast(:MONTO as numeric(18,0)) AS VARCHAR),
		:CODIGO,
		:DOCENTRY,
		:MONTO,
		'N',
		'N',
		'N',
		'N',
		'Y',
		:TIPODOCUMENTO,
		:NROCUOTA,
		:LINEAASIENTO,
		:CUENTAPROVEEDOR,
		:CODIGOBANCO,
		:CARDCODE_FACTO,
		:CARDNAME_FACTO
	);
END;