CREATE PROCEDURE "SMC_APM_REG_ESCENARIODET"
(
	CODIGO INT,
	DOCENTRY INT,
	MONTO DECIMAL(16,2),
	USUARIOCONECTADO VARCHAR(50),
	TIPODOCUMENTO VARCHAR(50),
	NROCUOTA INT,
	LINEAASIENTO INT
)
AS
BEGIN
--select * from "@SMC_APM_ESCDET"
	INSERT INTO 
		"@SMC_APM_ESCDET"
	VALUES
	(
		CAST(:DOCENTRY AS VARCHAR) || CAST(:CODIGO AS VARCHAR),--||CAST(cast(:MONTO as numeric(18,0)) AS VARCHAR),
		CAST(:DOCENTRY AS VARCHAR) || CAST(:CODIGO AS VARCHAR),--||CAST(cast(:MONTO as numeric(18,0)) AS VARCHAR),
		:CODIGO,
		:DOCENTRY,
		:MONTO,
		'N',
		'N',
		'N',
		'N',
		'Y',
		:TIPODOCUMENTO,
		:NROCUOTA,
		:LINEAASIENTO
	);
END;