//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC_APM.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMC_APM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMCPAGMAS.
        /// </summary>
        internal static string codMenu1 {
            get {
                return ResourceManager.GetString("codMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 43538.
        /// </summary>
        internal static string codMenuSAP1 {
            get {
                return ResourceManager.GetString("codMenuSAP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMCPAGMASPRO.
        /// </summary>
        internal static string codSubMenu1 {
            get {
                return ResourceManager.GetString("codSubMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMCPAGMASDET.
        /// </summary>
        internal static string codSubMenu2 {
            get {
                return ResourceManager.GetString("codSubMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string codSubMenu3 {
            get {
                return ResourceManager.GetString("codSubMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string codSubMenu4 {
            get {
                return ResourceManager.GetString("codSubMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmSMC6&quot; title=&quot;SMC - Reporte Cuentas por pagar informadas a SUNAT&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;593&quot; height=&quot;432&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;dta_1_1&quot;&gt;
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmReporteRCArchivo {
            get {
                return ResourceManager.GetString("frmReporteRCArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmSMC4&quot; title=&quot;SMC - Reporte RC Embargo&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;525&quot; height=&quot;432&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;dta_1_1&quot;&gt;
        ///              &lt;Columns /&gt;
        ///      [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmReporteRCEmbargo {
            get {
                return ResourceManager.GetString("frmReporteRCEmbargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmSMC5&quot; title=&quot;SMC - Reporte RC Liberación&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;525&quot; height=&quot;432&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;dta_1_1&quot;&gt;
        ///              &lt;Columns /&gt;
        ///   [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmReporteRCLiberacion {
            get {
                return ResourceManager.GetString("frmReporteRCLiberacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmSMC2&quot; title=&quot;SMC - Pagos Masivos Cuentas&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;933&quot; height=&quot;595&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;dtaFact&quot;&gt;
        ///              &lt;Columns /&gt;
        ///   [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmSMC_PM_DatosCuenta {
            get {
                return ResourceManager.GetString("frmSMC_PM_DatosCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;FrmLPG&quot; FormType=&quot;FrmLPG&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;FrmLPG&quot; title=&quot;Tercero Retenedor - Liberar Pagos&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;800&quot; height=&quot;500&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;EXD_OTRR&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_0&quot;&gt;
        ///           [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmSMC_PM_LiberarTerceroRet {
            get {
                return ResourceManager.GetString("frmSMC_PM_LiberarTerceroRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;frmSMC&quot; FormType=&quot;frmSMC&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmSMC1&quot; title=&quot;Escenarios de pago&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;930&quot; height=&quot;574&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;dtaFact&quot;&gt;
        ///              &lt;Columns /&gt;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmSMC_PM_PagoProveedores {
            get {
                return ResourceManager.GetString("frmSMC_PM_PagoProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMC_Pagos_Masivos.
        /// </summary>
        internal static string nombreAddon {
            get {
                return ResourceManager.GetString("nombreAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a frmSMC1.
        /// </summary>
        internal static string nomFormulario1 {
            get {
                return ResourceManager.GetString("nomFormulario1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos Masivos.
        /// </summary>
        internal static string nomMenu1 {
            get {
                return ResourceManager.GetString("nomMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escenarios de pago.
        /// </summary>
        internal static string nomSubMenu1 {
            get {
                return ResourceManager.GetString("nomSubMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos Masivos Detracciones.
        /// </summary>
        internal static string nomSubMenu2 {
            get {
                return ResourceManager.GetString("nomSubMenu2", resourceCulture);
            }
        }
    }
}
